go.mod
go.sum
relayer/chainproxy/chainproxy.go
relayer/chainproxy/jsonRPC.go
relayer/lavasession/consumer_session_manager.go
relayer/lavasession/errors.go
relayer/sentry/sentry.go
relayer/server.go
scripts/pre_setups/init_gth_only.sh
scripts/pre_setups/init_lava_grpc.sh

- [V] Commit message follows the Contribution Guidelines
- [V] Tests ran locally and added/modified if needed
- [V] Docs have been added/updated, if applicable
- [V] If applicable - JIRA ticket ID was added
Bug fix for session sync loss, added status error code between provider and consumer processes, to analyze if the session sync was lost, increased the consumer context timeout to wait a few MS longer than the provider to prevent context cancel races resulting in fewer session sync losses. 
https://lavanet.atlassian.net/browse/PRT-221?atlOrigin=eyJpIjoiZDY1M …

PRT-221 consumer requested a smaller relay num than expected trying to overwrite past usage

---

scripts/init_e2e.sh
scripts/init_e2e_lava_over_lava.sh
testutil/e2e/e2e.go

This PR does the following.
- Create proposal, vote and add providers and clients for a new network.
- Check if the txs are reflected onchain.
- Change the kill style for the proxy routine to interrupt so it properly gives up the port.
- Only print the errors from cmd.Wait() if the test is not done successfully. The current one prints out signal is killed errors because finishTestSuccessfully() kills them first before realizing the test is done because of the cmd.Wait().

PRT-206 add lava txs to e2e lava over lava txs validate they happened on chain

---

x/conflict/keeper/vote.go
x/conflict/types/expected_keepers.go
x/conflict/types/types.go
x/pairing/keeper/msg_server_unstake_client.go
x/pairing/keeper/msg_server_unstake_provider.go
x/pairing/keeper/stakeModify.go
x/pairing/keeper/unstaking.go
x/pairing/types/types.go

- [ v ] Commit message follows the Contribution Guidelines
- [ v ] Tests ran locally and added/modified if needed
- [ v ] Docs have been added/updated, if applicable
- [ v ] If applicable - JIRA ticket ID was added
feature - Add events messages for unstaking
The only unstake-related event is when the unstaker's money is returned to him. There are no events when the unstake is done or for when the unstake is automatic due to unresponsive provider / vote fraud
All unstake-related scenarios have …

CNS-131: added events for unstaking

---

relayer/lavasession/consumer_session_manager.go
relayer/lavasession/consumer_session_manager_test.go
relayer/lavasession/consumer_types.go

Adding support for multiple no pairings resets. (after no pairings are available we try to go over the pairing list again)
currently, we reach a point where there is an issue and we ban the provider for the remaining of the epoch, this can result in many idle epochs waiting for an epoch to change to get a different pairing list. 
after the entire provider list is blocked, we reset them and try again, instead of waiting for the remaining of the epoch. 
* **Please describe what manual tests you ran, …

PRT-273 when we have 0 providers left in pairing un block all providers and retry

---

docs/static/openapi.yml
relayer/sentry/sentry.go
relayer/server.go
scripts/pre_setups/init_chain_commands_one_provider.sh
scripts/pre_setups/setup_provider.sh

Retry mechanism for sequence number errors on payment requests by the expected sequence number. 
Also, splitting the payment requests into a random block in an epoch instead of all payment requests on the first block.
currently fails and doesnt parse the errors correctly and always asking rewards on the first block in an epoch 
Retry mechanism for sequence number errors on payment requests by the expected sequence number. 
Also, splitting the payment requests into a random block in an epoch instead …

PRT-292 incorrect account sequence no payments to providers

---

relayer/chainproxy/chainproxy.go
relayer/chainproxy/jsonRPC.go
relayer/chainproxy/portalLogs.go
relayer/chainproxy/rest.go
relayer/chainproxy/tendermintRPC.go

BugFix
The current implementation is missing " on some response attributes. Because of this we can not parse all responses
All responses should be parsable
I've manually tested all error responses and non have parsing issue anymore, also i tried to construct the malicious XSS attack and the marshal escapes all special characters

Add missing quotes on response

---

relayer/sentry/tx.go

PRT-377 gas adjustments

---

.github/workflows/e2e.yml
testutil/e2e/allowedErrorList.go
testutil/e2e/e2e.go

Include the logName that contains errors in the panic
Cleanup e2e.yml
Give each provider a different buffer

PRT-379 Fix only one provider log getting printed to log file

---

cookbook/spec_add_arbitrum.json
cookbook/spec_add_cosmoshub.json
cookbook/spec_add_fantom.json
cookbook/spec_add_juno.json
cookbook/spec_add_osmosis.json
cookbook/spec_add_polygon.json
docs/static/openapi.yml
testutil/keeper/keepers_init.go
x/epochstorage/keeper/stake_storage.go
x/pairing/keeper/grpc_query_static_providers_list.go
x/pairing/keeper/msg_server_stake_unstake_gov_test.go
x/pairing/keeper/pairing.go
x/pairing/keeper/pairing_test.go
x/pairing/types/expected_keepers.go

this is a bug fix, removing core.block from pairing as it is not determinitic

Cns 266 remove core.block and use instead blockhash that is saved in storage

---

app/app.go
app/upgrades/v0_5_0/upgrade.go
x/epochstorage/keeper/stake_storage.go

CNS upgrade plan 0.5.0

---

x/spec/types/spec.go

add validation to the spec parameters

---

app/app.go
app/encoding.go
app/params/encoding.go
app/simulation_test.go
app/test_helper.go
app/upgrades/v0.2.0/upgrade_test.go
app/upgrades/v0_X_0/upgrade_test.go
app/upgrades/v5/upgrade_test.go
cmd/lavad/cmd/config.go
cmd/lavad/cmd/genaccounts.go
cmd/lavad/cmd/root.go
cmd/lavad/main.go
docs/static/openapi.yml
go.mod
testutil/network/network.go

`cosmoscmd` has been deprecated and it's a good idea to remove any use of it from the codebase.

chore: remove `cosmoscmd`

---

app/app.go
app/upgrades/empty_upgrades.go
x/projects/keeper/msg_server_set_project_policy.go
x/projects/keeper/project.go
x/projects/types/project.go

**Upgrade plan from v0.7.1 to v0.8.1.**
In v0.8.1 the StoreKey of module Projects changed from "projects" to "project". The store upgrade handler deletes the old storage and adds the new one. (Note that as of cosmos-sdk 0.45.11 the "Renamed" method for store upgrade did not work properly).
Disable the attempt for v0.8.0 (which left out the above change), because it led to a corrupt store state, and could not be easily re-upgraded to a working state.
**How to test:**
1. Checkout/compile lavad-v0.7.1, install the `lavad` binary
2. Start the server with ignite:  `ignite chain server`
3. Run `scripts/init_chain_commands.sh`
4. Test the following commands:
```
curl http://127.0.0.1:3333/1/ --request POST --header "Content-Type: application/json" --data '{ "jsonrpc":"2.0", …
```

Upgrade plan v0.8.1

---

x/pairing/keeper/unresponsive_provider.go

Providers just recently staked, or just recently unfrozen, do not have enough history to properly judge their performance and QoS. Therefore, exclude them from consideration of unresponsive providers.

CNS-348: do not jail providers with too short history

---

protocol/chainlib/tendermintRPC.go

Added an HTTP connector to tendermintRpcChainProxy for all incoming relays, with the exception of the 'subscribe' process.

PRT-466-prefer-to-use-http-over-ws-where-possible-from-main

---

common/fixation_entry.go
common/fixation_entry_test.go
common/types/errors.go
x/plans/keeper/plan.go
x/plans/keeper/plan_test.go
x/projects/keeper/creation.go
x/projects/keeper/msg_server_set_project_policy.go
x/projects/keeper/project.go
x/subscription/types/expected_keepers.go

Change GetEntry,FindEntry to not return an error, use MustUnmarshal() instead of Unmarshal(). Change PutEntry to not return anything and not fill the entry whose refcount is being dropped (caller must already have it).
Previously they returned an error if the Ummarshal of the entry data failed. However that was bad for two reasons: first, such a failure would indicate a severe logical bug because the very same data must have been marshaled and saved before - hence it must be either corrupted or a new lava version now expects some different format (either way it's a bug). Second, callers do not have a way to rectify such errors, they just treat it as "not found", making it useless.

CNS-368: fixation: improve API for GetEntry,FindEntry,PutEntry

---

docker/start_provider.sh
scripts/init_chain_commands.sh
scripts/init_chain_subscriptions.sh
scripts/init_e2e.sh
scripts/init_e2e_lava_over_lava.sh
scripts/init_lava_over_lava.sh
scripts/pre_setups/init_arbitrum_only_test.sh
scripts/pre_setups/init_lava_only_test.sh
scripts/scripts_archive/test_unstake_provider.sh
x/pairing/client/cli/tx_stake_provider.go
x/pairing/types/errors.go
x/pairing/types/message_stake_provider.go
x/pairing/types/message_stake_provider_test.go
x/pairing/types/types.go

In this PR, I've made the "moniker" field of the stake-provider command mandatory and without a default value. I've also limited the moniker's length to be 50 characters or less.
Note that the moniker flag's name was changed to "provider-moniker"

CNS-357: make the provider's moniker field mandatory

---

protocol/chainlib/chainproxy/rpcInterfaceMessages/grpcMessage.go
protocol/chainlib/chainproxy/rpcInterfaceMessages/restMessage.go
protocol/chainlib/chainproxy/rpcInterfaceMessages/restMessage_test.go
protocol/chainlib/common.go
protocol/chainlib/common_test.go
protocol/chainlib/grpc.go
protocol/chainlib/rest.go
protocol/chainlib/rest_test.go
protocol/parser/parser.go
protocol/rpcprovider/rewardserver/reward_server.go
protocol/rpcprovider/rpcprovider_server.go

The requested block has been added to the `newChainMessage`, replacing the prior usage of `spectypes.NOT_APPLICABLE` for both REST and gRPC interfaces.

 PRT-167-Data-reliability-for-rest-tendermint-grpc-optional-params

---

common/fixation_entry.go
common/fixation_entry_test.go
common/types/errors.go
x/plans/keeper/plan.go
x/plans/keeper/plan_test.go
x/projects/keeper/creation.go
x/projects/keeper/msg_server_set_project_policy.go
x/projects/keeper/project.go
x/subscription/types/expected_keepers.go

This reverts commit a62abec1142365afc46f47a3fcff6b5f4d9938ca. 
(It restores commit f22c5c70c81af559f70e4debbde7c5f0f159a9a4).

Restore "CNS-368: fixation: improve API for GetEntry,FindEntry,PutEntry…"

---

common/fixation_entry.go
common/fixation_entry_index.go
common/fixation_entry_test.go
common/types/fixationEntry.go
x/plans/keeper/keeper.go
x/plans/module.go
x/projects/keeper/keeper.go
x/projects/module.go
x/subscription/keeper/subscription.go

Fix refcount handling: FixationStore entry refcount was half-baked: the latest entries had refcount 0, and the code had special handling to avoid ignoring/removing them.
Fix garbage collection logic for stale entries: (1) When entries get StaleAt field set, set a timer to fire on that block; (2) Whenever such timer fires, scan all versions of the respective index to remove eligible stale versions ("eligible" stale version is one whose preceding version is stale; the oldest version is always "eligible").

CNS-368: fixation store fix refcount and deletions

---

protocol/lavasession/end_to_end_lavasession_test.go
protocol/lavasession/provider_session_manager.go
protocol/lavasession/provider_session_manager_test.go
protocol/lavasession/provider_types.go
protocol/rpcprovider/rpcprovider.go
protocol/rpcprovider/rpcprovider_server.go
protocol/statetracker/provider_state_tracker.go
protocol/statetracker/state_query.go

Following a data reliability message, the provider verifies that it indeed is the designated provider by checking that its "self" vrfIndex matches that of the client.
This got broken with the use of subscription in E2E tests, becuase the default plan uses 5 providers while E2E uses 2 providers, the while the consumer uses the number of providers from the pairing, the provider gets it from the plan. Since they disagree, the VRF output also (likely) differs and triggers error.
The error message was:
testutil/e2e/logs/05_LavaProvider_01_errors.log:Apr  2 08:10:13 ERR
Provider identified invalid vrfIndex in data reliability request, the given
index and self index are different GUID=16864668971218711883....
Actually, in the non-subscription case, the providers gets that number from the params. …

CNS-374: fix vrfIndex mismatch between consumer and provider

---

cookbook/specs/spec_add_bsc.json
cookbook/specs/spec_add_cosmossdk.json
cookbook/specs/spec_add_cosmossdk_full.json
cookbook/specs/spec_add_cosmoswasm.json
cookbook/specs/spec_add_ibc.json
cookbook/specs/spec_add_solana.json
x/spec/types/spec.go

added check in spec proposal handler that spec name can only have lowercase chars or ' '.
After talking with @SeanZoR , existing specs should already have all lowercase chain names.

CNS-261: enforce lowercase in spec names

---

common/fixation_entry.go
common/fixation_entry_index.go
common/fixation_migrate.go
common/fixation_migrate_test.go
common/types/fixationEntry.go
protocol/chainlib/chainproxy/connector.go
x/plans/keeper/migrations.go
x/plans/module.go
x/plans/types/keys.go
x/projects/keeper/migrations.go
x/projects/module.go

This PR creates a new migration v2 to v3 of FixationStore to fix the use of prefix.
It also creates an upgrade to modules "plan" and "project" to run this migration.
Finally, it changes the prefix used by module "plan" to be consistent with our naming.

CNS-382 fixation update prefix

---

testutil/keeper/keepers_init.go
x/conflict/keeper/keeper.go
x/conflict/keeper/vote_test.go
x/conflict/module.go
x/epochstorage/keeper/keeper.go
x/epochstorage/module.go
x/pairing/keeper/keeper.go
x/pairing/keeper/msg_server_relay_payment_test.go
x/pairing/keeper/unresponsive_provider_test.go
x/pairing/module.go
x/pairing/types/types.go
x/spec/keeper/keeper.go
x/spec/module.go
x/subscription/keeper/epoch_start_test.go
x/subscription/keeper/keeper.go
x/subscription/keeper/subscription_test.go
x/subscription/module.go
x/subscription/types/expected_keepers.go

I made the NewBlock() function iterate over all keepers and call their corresponding BeginBlock() callback (instead of calling the inner functions directly). Also fixed some unit tests issues

CNS-446: fix testutils block advancement simulation

---

common/fixation_entry.go

Testing for IsStaleBy() should always be against ctx.BlockHeight(), and for IsDeletedBy() aganst the target (look-up) block.

CNS-428: fix test for IsStaleBy in FindEntry()

---

docs/static/openapi.yml
proto/subscription/tx.proto
scripts/init_e2e.sh
testutil/e2e/e2e.go
x/pairing/keeper/msg_server_relay_payment_test.go
x/pairing/keeper/pairing_subscription_test.go
x/projects/keeper/creation.go
x/projects/keeper/project.go
x/projects/keeper/project_test.go
x/subscription/client/cli/tx.go
x/subscription/client/cli/tx_del_project.go
x/subscription/handler.go
x/subscription/keeper/msg_server_del_project.go
x/subscription/keeper/subscription.go
x/subscription/keeper/subscription_test.go
x/subscription/module_simulation.go
x/subscription/simulation/del_project.go
x/subscription/types/codec.go
x/subscription/types/expected_keepers.go
x/subscription/types/message_del_project.go
x/subscription/types/message_del_project_test.go
x/subscription/types/tx.pb.go
x/subscription/types/types.go

Add logic and tx commands to delete projects.
Change tx subscription add-project semantics to take effect at the end of the current epoch.
The new tx subscription del-project also takes effect at the end of the current epoch.
Adjust semantics of tx project set-policy to also take effect at the end of the current epoch.
Adjust testing to ensure that this operations has enough time/blocks to take effect.

CNS-421: allow project delete

---

protocol/lavasession/consumer_session_manager_test.go
protocol/lavasession/end_to_end_lavasession_test.go

In our codebase, we had a problem where lavasession unit tests were not running because we make a mistake while initializing them.
To create grpc server before every test we've used
```
func TestMain(m *testing.M){
createGRPCServer()
}
```
but inside of it, we haven't called any tests. This PR adds a test run for every test case and also fixes tests which were failing
This PR enables lavassesion tests on every PR, but if anyone wants to run them individually, you can use
```
go test ./protocol/lavasession/...
```
This PR doesn't refactor existing tests, it just enables them and makes sure that they are passing

[PRT-702] Enable add fix lavasession tests

---

cookbook/projects/example_policy.yml
scripts/init_e2e.sh
testutil/e2e/e2e.go
x/plans/types/plan.pb.go
x/subscription/client/cli/tx_add_project.go

- fix e2e.go to check for exit status of init_e2e.sh
- fix syntax in init_e2e.sh (subscription add-project)
- fix cookbook/projects/example_poliicy.yml
- fix reading of project policy yml file
- leftover update of .../types/plan.pb.go from ealier PR

CNS-501 e2e fails subscription add project

---

common/fixation_entry.go
x/pairing/keeper/pairing_immediately_test.go
x/projects/keeper/creation.go
x/projects/keeper/project.go
x/projects/keeper/project_test.go
x/projects/types/project.go

Changes are non-trivial the handle the following two cases:
1. delete a key handles admin key immediately, but developer key deferred to beginning of next epoch.
2. add a key after a previous delete key in the same epoch (which created a future entry); not necessarily the same key.

CNS-479 add project key effective now

---

proto/spec/api_collection.proto
utils/lavalog.go
x/spec/keeper/spec.go
x/spec/keeper/spec_test.go
x/spec/proposal_handler.go
x/spec/types/types.go

When a Spec gets updated, we set its BlockLastUpdated field to the current
block height (useful for producers to know whether they use the latest Spec
version).
If there are other Specs that inherit this Spec, then they effectively also
changed - so we hunt them and set their BlockLastUpdated field too.

CNS-443 propagate spec change to descendants

---

protocol/rpcprovider/rpcprovider.go

This PR fixes a bug where we are not validating chainId for all interfaces, but only till first valid
```
screen -d -m -S provider1 bash -c "source ~/.bashrc; lava-protocol rpcprovider \
$PROVIDER1_LISTENER COS3 rest '$OSMOT_REST' \
$PROVIDER1_LISTENER COS3 tendermintrpc '$OSMO_RPC,$OSMO_RPC' \
$PROVIDER1_LISTENER COS3 grpc '$OSMOT_GRPC' \
$EXTRA_PROVIDER_FLAGS --metrics-listen-address ":7780" --geolocation 1 --log_level debug --from servicer1 2>&1 | tee $LOGS_DIR/PROVIDER1.log" && sleep 0.25
```
```
Jul 20 08:41:51 ERR RPCProvider running with disabled endpoints:
COS3:rest Network Address:127.0.0.1:2221 Node: https://bekotopopo2:99al9YwXTnvJohMW39ZBqVH5AWnWBDV8@prod-pnet-osmosisnode-1.lavapro.xyz/testnet/rest/ Geolocation:1 Addons:
COS3:grpc Network Address:127.0.0.1:2221 Node: …
```

[PRT-786] Validate chain id for all rpc interfaces

---

protocol/rpcprovider/rewardserver/badger_db.go
protocol/rpcprovider/rewardserver/db.go
protocol/rpcprovider/rewardserver/reward_db.go
protocol/rpcprovider/rewardserver/reward_db_test.go
protocol/rpcprovider/rewardserver/reward_server.go
protocol/rpcprovider/rewardserver/reward_server_test.go
protocol/rpcprovider/rpcprovider.go
protocol/statetracker/provider_state_tracker.go
utils/lavalog.go
utils/logger_wrapper.go

This PR fixes a case where rewards are being sent for an epoch too far in the past, and adds a configurable time to live to stored rewards.
Builds on top of #620

[PRT-750] persist provider rewards (#583) (by agilefreaks)

---

common/fixation_entry.go
common/fixation_entry_test.go

Solves https://lavanet.atlassian.net/browse/CNS-490
PutEntry() decrements the refcount of an entry. When the refcount reaches zero, the entry is transitioned into stale-period. However, future entries by definition never get to be used/references, so for future entries the stale-period should not happen - they should be skipped.

CNS-490: fixation handle future entry put

---

go.mod
go.sum
testutil/common/tester.go
utils/rand/rand.go
utils/rand/rand_test.go
x/pairing/keeper/pairing_test.go
x/pairing/keeper/scores/score.go

Using the global rand directly is not safe in terms of determinism, e.g. if
another go routine calls (now or in the future) it to get a random number at
the wrong time. Likewise, rand.Seed() is deprecated in Go (for very similar
reasons).
Also, Go does not guarantee that the PRNG driving the default source for rand
will always provide the same output for a given seed - across different Go
versions.
Instead, implement our own source (PRNG) that combines rand.New() to provide
a dedicated (private) instance of a PRNG that uses the xoroshiro256** PRNG
from the the xorshift package as a source.
(See https://en.wikipedia.org/wiki/Xorshift for more details)

CNS-516: fix rand to ensure determinism

---

go.mod
go.sum
protocol/badgegenerator/badgeserver.go
protocol/badgegenerator/constants.go
protocol/badgegenerator/metrics.go
protocol/badgegenerator/server.go

During the badge request, record:
1. How many request for badge generation was received
2. How many badges created successfully
3. How many badges failed to create
Add “/metrics” http endpoint and output the above metrics in prometheus format

GROW-453 Add usage metrics on badges.

---

protocol/metrics/analytics.go
protocol/metrics/metricsService.go

BUG FIX:
- Send the corresponding date of the relays when doing HTTP call

GROW-950 Add timestamp when sending relays data from rpc consumer

---

cookbook/specs/spec_add_starknet.json

Missing APIs in our starknet spec:
- `starknet_addInvokeTransaction`
- `starknet_addDeclareTransaction`
- `starknet_addDeployAccountTransaction`
- `starkent_estimateMessageFee`
Also, none of our current spec APIs are deprecated

CNS: add missing APIs to Starknet spec

---

x/pairing/keeper/grpc_query_user_entry.go
x/pairing/keeper/limitConsumer.go
x/plans/types/policy.go

the UserEntry query, which is used in both consensus and protocol code, didn't verify the CU usage correctly. The CU usage was compared against a wrong value of total CU

CNS-BUG-FIX: make VerifyTotalCuUsage work with effective total cu

---

protocol/chainlib/common.go
protocol/chainlib/common_test.go
protocol/chainlib/grpc.go
protocol/chainlib/jsonRPC.go
protocol/chainlib/rest.go
protocol/chainlib/tendermintRPC.go
testutil/e2e/protocolE2E.go

In our current implementation, dappID is inside path which makes requests more complicated and there is no way to support optional dappID-s. THis PR fixes this problem by moving the dappID in headers and if user does not specify it it will auto-generate new dappID
```
1.  Post
curl -X POST -H "dappId: dappID\_8765"/ "127.0.0.1:3360/cosmos/base/tendermint/v1beta1/node\_info"
curl -X POST "127.0.0.1:3360/cosmos/base/tendermint/v1beta1/node_info"
2.  Get
curl -X GET "127.0.0.1:3360/cosmos/base/tendermint/v1beta1/node_info"
curl -X GET -H "dappId: dappID\_12345" "127.0.0.1:3360/cosmos/base/tendermint/v1beta1/node\_info"
1.  Post
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:3333 --data '{"jsonrpc":"2.0","id":535439332833,"method":"eth_blockNumber","params":\[\]}'
curl -X …
```

PRT-784 Move dappID from path to headers

---

scripts/init_chain.sh
scripts/init_chain_commands.sh
scripts/init_install.sh
scripts/protocgen.sh
scripts/useful_commands.sh

init_chain.sh - if `jq` is not installed, the script fails. Added jq installation
init_chain_commands.sh - added another `wait_next_block` after proposals to avoid statistical `account sequence mismatch` error

CNS-578: small fixes for init chain scripts

---

testutil/common/tester.go
x/pairing/keeper/helpers_test.go
x/pairing/keeper/msg_server_stake_provider_test.go
x/pairing/keeper/msg_server_stake_unstake_gov_test.go
x/pairing/keeper/pairing_test.go
x/pairing/keeper/unresponsive_provider_test.go

There was a small bug in the endpoints generation in out testing suite. Also added error checks when staking providers

CNS-580: let multi-geo values work in our unit tests

---

cookbook/specs/spec_add_axelar.json

Missing APIs:
axelar.evm.v1beta1.QueryService/Command
axelar.nexus.v1beta1.QueryService/Message
axelar.reward.v1beta1.QueryService/InflationRate
axelar.reward.v1beta1.QueryService/Params
All the APIs that were in the spec from before are still supported
EDIT: checked new APIs - got response from provider

CNS-581: added missing APIs for Axelar

---

ecosystem/lavavisor/pkg/process/fetcher.go
ecosystem/lavavisor/pkg/process/version_monitor.go
ecosystem/lavavisor/pkg/util/common.go

* Added a robust mechanism to attempt fetching lava-protocol version starting from target version to minimum version in descending order
* General improvements and small bug fixes:
1. changed protocolPath for building the binary to 'cmd/lava-protocol'
2. added 'ValidateProtocolVersion' check after fetching & building the binary (old versions of lava-protocol will not be supported by lava-visor anymore)

Lavavisor improvements

---

ecosystem/lava-sdk/src/lavasession/consumerSessionManager.ts
ecosystem/lava-sdk/src/lavasession/consumerTypes.ts

This PR adds an optional argument that allows transport options to be set on the `ConsumerSessionManager`.
Usage:
```typescript
new ConsumerSessionManager(
// ...,
{
transport: transport, // or transportAllowInsecure
}
)
new ConsumerSessionManager(
// ...,
{
allowInsecureTransport: false, // or true. by default it's always false
}
)
new ConsumerSessionManager(
// ...,
{
transport: transport, // or transportAllowInsecure
allowInsecureTransport: true, // does nothing in this case as transport is already supplied
}
)
```

[PRT-867] Add options arg to pass through transport in `ConsumerSessionManager`

---

ecosystem/lavavisor/cmd/create-service.go
ecosystem/lavavisor/cmd/start.go
ecosystem/lavavisor/pkg/process/process_manager.go
ecosystem/lavavisor/pkg/process/version_monitor.go
ecosystem/lavavisor/pkg/util/common.go

- symlink created for generated service files to root "/etc/systemd/system/" -> this is where service files are read by default
- 'start' command will now traverse `upgrades/` directory and choose the most recent version dir as its working path (ensuring selected version is between min and target version)
- typo fix for service file generation

Lavavisor improvements v2

---

protocol/chainlib/jsonRPC.go
protocol/chainlib/rest.go
protocol/chainlib/tendermintRPC.go

Description:
In our current implementation we are returning responses with header content-type: text/plain.This PR fixes it and makes it as application/json

PRT-883 Fix content type in HTTP response

---

scripts/protocgen.sh
scripts/useful_commands.sh

The build 'make proto-gen' stopped working because the 'proto-build' docker image from cosmos no longer supports bash. Fix by adjusting the script to be compatible with 'sh' instead of 'bash'.

CNS-593: fix "make proto-gen" breakage

---

common/fixation_entry.go
common/fixation_entry_test.go

DelEntry() of future entry normally searches for a strictly nearest-smaller previous entry (rather than nearest-no-later). For rationale see comments in the code.
However, that logic assumes that there is at least one previous version to the affected future entry, and otherwise fails to delete a future entry that does not have such previous current version.
To fix that, check for this kind of exception - a (first) future entry that has not matured yet, i.e. that has no current version of the entry in place. If found, then trim the entire cadence.
Also fix a missing call to delete the timer of the canceled future entry in cancelEntry(); Rename to putFutureEntry() and refactor trimFutureEntries().
Add unit test for this DelEntry() special case.

CNS-597: fixation delete future entry first

---

testutil/common/mock.go
x/conflict/keeper/msg_server_detection_test.go
x/pairing/keeper/helpers_test.go
x/pairing/keeper/pairing_subscription_test.go
x/pairing/keeper/pairing_test.go
x/projects/keeper/project_test.go
x/subscription/keeper/cluster_test.go
x/subscription/keeper/subscription_test.go

This was done so the clustering code won't print lots of errors because there's no "mock" plan

CNS-595: changed mock plan index to "free"

---

protocol/chainlib/chainproxy/rpcclient/client.go
protocol/chainlib/chainproxy/rpcclient/http.go
protocol/chainlib/jsonRPC.go
protocol/chainlib/node_error_handler.go
protocol/chainlib/rest.go
protocol/chainlib/tendermintRPC.go
protocol/rpcprovider/reliabilitymanager/reliability_manager_test.go

**Changelog**
- Added a check for response status codes 504 and 429 in REST and Tendermint URI calls. (Note: For JSON-RPC and Tendermint-RPC, this is already handled by the doRequest function in http.go).
- Implemented a JSON format validation for all REST API responses.
- Introduced an ID verification step for both JSON-RPC and Tendermint-RPC.
**Manual Testing**
- Conducted tests by sending requests to a server configured to always return status codes 504 and 429. Verified that the new status code checks are operational.
- Reviewed provider logs and confirmed that for successful relay transactions, no errors were generated due to JSON formatting issues or ID discrepancies.

PRT-847: Providerside Error Handling

---

testutil/common/tester.go
utils/slices/slices.go
utils/slices/slices_test.go
x/pairing/keeper/pairing_test.go

Filter() takes a slice and returns a sub-slice based on an input filter function applied on each of the elements of the slice.
Also rename the old Filter() to what it really is - Map(), which take a slice and returns a new slice with the result of applying the input map function on the elements of input slice.

feat: add slices helper Filter()

---

helm/provider/templates/deployment.yaml
helm/provider/values.yaml

1. When using the `latest` tag, `pullPolicy` should be set to `Always` to avoid image caching. Overall using `latest` is not recommended and it's better to use a particular pinned version
2. Added checksum for the configmap so that the pod restarts when the configmap is changed
3. Fixed syntax for probe cmd which was not working correctly

Helm improvements

---

scripts/init_chain_commands.sh
scripts/simulate_reward_payment.sh
x/pairing/client/cli/tx.go
x/pairing/client/cli/tx_simulate_relay_payment.go

<h2>Description</h2>
This PR implements a CLI command for simulating reward payment operation without the need for bootstrapping providers. It creates`RelaySession` object, wraps it into a message and sends it to network.
**Example Command:**
`lavad tx pairing simulate-relay-payment user1 LAV1 --from servicer1 --cu-amount 222 --gas-prices 0.00001ulava --gas-adjustment "1.5" --gas "auto" --relay-num 50 --yes`
<h2>Automatization</h2>
`simulate_reward_payment.sh` script does the following :
- Executes the `init_chain_commands.sh` script **without initializing providers.**
- Retrieves and displays the initial balance of the `servicer1` provider.
- Runs the CLI command to simulate reward payment.
- Fetches and displays the final balance of `servicer1`.
- Compares the initial and final …

CNS-610: Add tx capabilities without the protocol

---

ecosystem/lava-sdk/src/chainlib/base_chain_parser.ts
testutil/e2e/sdk/tests/tendermintrpc_chainid_fetch.ts
testutil/e2e/sdk/tests/tendermintrpc_named_params.ts

Add support for tendemint named params in SDK.
Manual test:
```
const cosmosHub = await LavaSDK.create({
// private key with an active subscription
privateKey:
<PrivKey>,
// chainID for Cosmos Hub
chainIds: "LAV1",
// geolocation 1 for North america - geolocation 2 for Europe providers
// default value is 1
geolocation: "1",
pairingListConfig: "pairingList.json",
lavaChainId: "lava",
logLevel: "debug",
allowInsecureTransport: true,
});
// Get abci_info
const info = await cosmosHub.sendRelay({
method: "block",
params: { height: "100" },
});
console.log("Info:", info);
```

[PRT-926] Enable named params in tendermint

---

protocol/rpcprovider/rpcprovider.go

The message "all endpoints up an running" is missing a 'd' for "and".

Fix typo in startup message

---

x/pairing/keeper/unresponsive_provider_test.go

In the unresponsive stress test, we had a random factor in which in some cases would cause the test to fail. The problem was (in general) that we picked some provider to be the test unresponsive provider and from time to time picked it to send a relay payment TX reporting on itself that it's unresponsive. This made it avoid punishment and fail the test.

CNS-671: stabilizing unresponsive unit test

---

cookbook/specs/spec_add_avalanche.json
cookbook/specs/spec_add_axelar.json
cookbook/specs/spec_add_fvm.json
cookbook/specs/spec_add_near.json
cookbook/specs/spec_add_solana.json

Added the following APIs to Axelar:
POST
/axelar/permission/deregister_controller
/axelar/permission/register_controller
/axelar/permission/update_governance_key
GET
/axelar/axelarnet/v1beta1/params
/axelar/evm/v1beta1/params/{chain}
/axelar/multisig/v1beta1/params
/axelar/nexus/v1beta1/params
/axelar/snapshot/v1beta1/params
/axelar/tss/v1beta1/params
/axelar/vote/v1beta1/params
/axelar/permission/v1beta1/params
Also fixed the "hanging_api" field in some specs

CNS-669: Axelar missing APIs

---

cookbook/specs/spec_add_fvm.json

Added:
Filecoin.ChainStatObj
Filecoin.ChainTipSetWeight
Filecoin.GasEstimateMessageGas
Filecoin.MpoolSub
Filecoin.StateCirculatingSupply
Filecoin.StateWaitMsg
Filecoin.StateWaitMsgLimited
Removed (deprecated):
Filecoin.ChainGetNode
Filecoin.ChainGetTipSetAfterHeight

CNS-670: updated FVM spec

---

x/subscription/keeper/migrations.go
x/subscription/module.go

In the testnet there are old subscriptions that don't have a timer counting down their expiry, thus effectively making them without expiry. In this migrator, I look for these subscriptions and manually start advanceMonth to fix the situation

CNS-691: trigger expiry for old subscriptions

---

cmd/lavad/cmd/genaccounts.go
x/conflict/client/cli/query_conflict_vote.go
x/conflict/client/cli/query_consumer_conflicts.go
x/conflict/client/cli/query_params.go
x/conflict/client/cli/query_provider_conflicts.go
x/downtime/client/cli/query.go
x/epochstorage/client/cli/query_epoch_details.go
x/epochstorage/client/cli/query_fixated_params.go
x/epochstorage/client/cli/query_params.go
x/epochstorage/client/cli/query_stake_storage.go
x/pairing/client/cli/query_epoch_payments.go
x/pairing/client/cli/query_params.go
x/pairing/client/cli/query_provider_payment_storage.go
x/pairing/client/cli/query_unique_payment_storage_client_provider.go
x/plans/client/cli/query_params.go
x/projects/client/cli/query_params.go
x/protocol/client/cli/query_params.go
x/spec/client/cli/query_params.go
x/spec/client/cli/query_spec.go
x/subscription/client/cli/query_params.go

To allow the --height flag to work, I replaced all GetClientContextFromCmd with GetClientQueryContext

CNS-756: fix queries support for --height flag

---

x/projects/keeper/creation.go
x/projects/keeper/project.go
x/projects/keeper/project_test.go
x/projects/types/types.go

In this PR, I've limited the number of project keys a project can hold in all times. Defined as a constant (current value = 10).

CNS-816: limit project keys

---

x/pairing/keeper/pairing_test.go
x/pairing/keeper/staking.go
x/pairing/types/types.go
x/projects/keeper/msg_server_add_project_keys.go
x/projects/keeper/msg_server_del_project_keys.go
x/projects/keeper/project_test.go

In this PR I capped the following TXs arguments:
- StakeProvider: max number of 5 endpoints per geolocation
- AddKeys/DelKeys: max number of 10 keys
All restrictions can be changed by changing the appropriate constant.
Note, other repeated fields in TXs were not changed as instructed by @Yaroms.

CNS-817: uncapped repeated fields

---

x/conflict/keeper/vote.go

Until the conflict module is more stable, we stop freezing providers as punishment

CNS-760: removed freeze from conflict

---

x/dualstaking/keeper/delegate.go

The following PR fixes the following bug:
The `delegations[i].Amount` is not reset to 0 if `delegations[i].Amount.Amount.LT.(amountToDeduct)` holds [here](https://github.com/lavanet/lava/blob/36fce686791af2648c97676cf176603a9b420edb/x/dualstaking/keeper/delegate.go#L534) , we suggesting setting `delegations[i].Amount = 0` as it could be used later when [here](https://github.com/lavanet/lava/blob/36fce686791af2648c97676cf176603a9b420edb/x/dualstaking/keeper/delegate.go#L552) are leftovers here.

CNS-843: delegations bug fix

---

testutil/common/tester.go
x/dualstaking/ante/disable_redelegation_hooks.go
x/dualstaking/ante/disable_redelegation_hooks_test.go

The following PR fixes the following bug:
Tests call `msgServer` functions directly (e.g. `ts.TxReDelegateValidator` is a wrapper around `StakingServer.BeginRedelegate`). This means that any logic in anteHandlers will be bypassed, and test environments might not properly reflect actual tx execution states.
Note that the only ante handler in our code refers to the staking module's redelegate msg, so I fixed its wrapper specifically.

CNS-844: call dualstaking ante handler + ante unit test

---

protocol/chainlib/chain_message.go
protocol/chainlib/chainlib.go
protocol/common/endpoints.go
protocol/rpcconsumer/rpcconsumer_server.go

By appending a dedicated http header to requests -> lava-force-cache-refresh

Allow rpcconsumer skip hitting the cache store

---

x/dualstaking/keeper/hooks_test.go
x/pairing/keeper/staking.go
x/pairing/types/expected_keepers.go

Fix a bug in which when a provider unstakes and then re-stakes, we didn't consider past delegations to it.
Now, when a provider stakes, we check the delegationFS for existing delegations and add it to its DelegateTotal field

CNS-848: when staking, add to delegate total past delegations

---

x/dualstaking/keeper/delegate.go
x/dualstaking/keeper/helpers_test.go
x/dualstaking/keeper/hooks.go
x/dualstaking/keeper/hooks_test.go
x/dualstaking/keeper/migrations.go

to test this i created a new validator (this is the same as delegate)
Gas before the change:
gas_used: "227102"
gas_wanted: "320769"
Gas after the change:
gas_used: "169884"
gas_wanted: "234942"

CNS-886-ignore-dualstaking-hooks-gas-consumption

---

common/types/ascii.go
common/types/ascii_test.go

fixed the following:
unicode.IsLetter doesn’t check if a given char is an ascii char, so non-ascii chars (e.g., あ, 漢) can pass [this check](https://github.com/lavanet/lava/blob/c3d7d35987adbd384fd75148ffdab96b12dc6cd0/common/types/ascii.go#L60), and [this condition](https://github.com/lavanet/lava/blob/c3d7d35987adbd384fd75148ffdab96b12dc6cd0/common/types/ascii.go#L36) isn’t met. Additionally, it seems like the index can be empty unlike name and description.

CNS-907: string validation fixes

---

x/pairing/keeper/msg_server_relay_payment.go

When iterating over relays, instead of validating the pairing for each relay, we keep track of the validated provider-consumer-spec trio in a local map and skip the validation if it was already validated in a previous relay

CNS-923: added local cache for validate pairing

---

.github/workflows/lint_pr.yml

* Automatically generating CHANGELOGs.
* Automatically determining a semantic version bump (based on the types of commits landed).
* Communicating the nature of changes to teammates, the public, and other stakeholders.
* Triggering build and publish processes.
* Making it easier for people to contribute to your projects, by allowing them to explore a more structured commit history.

DO-2177 Forcing Conventional Commits Rules on PRs

---

scripts/test_spec_full.sh

Fix error `Error: accepts 5 arg(s), received 6` when `spect_test_full.sh` run 
The $STAKE var is undefined, this PR defines var for `delegate-limit`, also `--delegate-limit`  can't be removed from the command, because cli rising error that this param is required

fix: define `--delegate-limit` var

---

cookbook/specs/spec_add_scroll.json

Does this look good? From what I can tell Scroll doesn't have any custom RPC methods on top of the Ethereum EVM spec.
Testing command:
```
./scripts/test_spec_full.sh cookbook/specs/spec_add_scroll.json jsonrpc https://rpc.scroll.io jsonrpc https://sepolia-rpc.scroll.io
```

feat: Add Scroll Spec

---

cookbook/specs/spec_add_base.json

Testing command was successful:
```
./scripts/test_spec_full.sh cookbook/specs/spec_add_base.json jsonrpc https://mainnet.base.org jsonrpc https://goerli.base.org jsonrpc https://sepolia.base.org
```

feat: Update Base spec to include new Sepolia testnet

---

cookbook/specs/spec_add_cosmossdk.json
cookbook/specs/spec_add_cosmoswasm.json
cookbook/specs/spec_add_ibc.json

I'm working on an Injective spec right now, and I noticed that some of the APIs listed in their docs are not in the cosmos specs. I double checked the cosmos repos and I found the methods Injective uses.
Cosmos repo links to added methods:
https://github.com/cosmos/ibc-go/blob/cf68eed722589ebfda122035a48303772a681ce6/proto/ibc/core/channel/v1/query.proto#L106
https://github.com/CosmWasm/wasmd/blob/e5260f03a0ffe5f4d069078b550e5c47f15c1394/proto/cosmwasm/wasm/v1/query.proto#L73
https://github.com/cosmos/cosmos-sdk/blob/2100a73dcea634ce914977dbddb4991a020ee345/proto/cosmos/upgrade/v1beta1/query.proto#L43
https://github.com/cosmos/cosmos-sdk/blob/2100a73dcea634ce914977dbddb4991a020ee345/proto/cosmos/params/v1beta1/query.proto#L23
https://github.com/cosmos/cosmos-sdk/blob/2100a73dcea634ce914977 …

fix: adding missing cosmos methods

---

ecosystem/cache/server.go

When deploying the cache service on a machine that already had one running the error: `bind failed. Error: Address already in use`.  Unlike TCP the sock file must be cleaned out of the filesystem after service exit.
Using `syscall.unlink` before creating the new unix socket makes sure that the filesystem is clean when creating a new one. 
This also makes sure that no matter how the program existed the socket will always be deleted.
Also using `SplitHostPort` and `ResolveUnixAddr` to properly parse and initiate the unix socket.
Aside from running locally, this was tested by coping the PR artifact to testing server, restarting the cache, then restarting it again and making sure IPRPC can reach it.

fix: unlink cache unix socket

---

x/rewards/keeper/helpers_test.go
x/rewards/keeper/iprpc_test.go

In this PR, I've edited the TestIprpcEligibleSubscriptions unit test to check IPRPC eligibility for: iprpc subscriptions owners, developers in the iprpc subscription's admin project, developers in the iprpc subscription's regular project

fix: CNS-972: enhanced the unit test for iprpc subscriptions

---

x/pairing/client/cli/tx_modify_provider.go

In this PR I deleted the limitation of reducing stake using the `modify-provider` TX. This was legacy code that was written when stake could not be partly reduced, so it's not relevant anymore.

fix: CNS-974: remove modify-provider limitation of reducing stake

---

ecosystem/lavavisor/pkg/process/fetcher.go

Closes: #1644
There was a mass-replacement for Lava v2 in commit 5864b7a. This resulted in the auto-download link being broken for Lavavisor. With this commit, the archive downloads can be successful again.
---
I have...
_no functional changes impacting testing_
_no functional changes warranting documentation changes_
I have...

fix: Use correct Github repository archive link

---

app/app.go
app/upgrades/empty_upgrades.go
x/pairing/keeper/migrations.go
x/pairing/module.go
x/protocol/module.go
x/protocol/types/params.go

Closes: #XXXX
---
I have...
I have...

fix: CNS-v3.1.0

---

.dockerignore
.github/workflows/lava.yml
cmd/lavad/Dockerfile
cmd/lavad/Dockerfile.Cosmovisor
cmd/lavap/Dockerfile

Closes: [#155](https://github.com/Magma-Devs/magma-devs/issues/155)
Update github workflow to parallel build docker images and test. thus speeding up the CI
---
I have...
I have...

ci: docker build speedup

---

testutil/e2e/allowedErrorList.go

There is already, `"connection refused"` in `allowedErrorsDuringEmergencyMode`, but now that the `"Connection refused"` is added as reason to errors when disconnecting the node,  as can be seen in this error log:
`ERR Provider Side Failed Sending Message, Reason: Connection refused`, `"Connection refused"` needed to be added as well.

fix: PRT - Fix failing E2E on emergency mode

---

scripts/automation_scripts/short_block_proposers.py

Closes: #XXXX
---
I have...
I have...

feat: CNS-short-block-script

---

protocol/chainlib/consumer_websocket_manager.go
protocol/common/cobra_common.go
protocol/rpcconsumer/rpcconsumer.go

Closes: #XXXX
---
I have...
I have...

feat: PRT - add ban duration for websocket rate limit exceeded

---

protocol/chainlib/consumer_websocket_manager.go
protocol/metrics/metrics_consumer_manager.go
protocol/metrics/rpcconsumerlogs.go

Closes: #XXXX
---
I have...
I have...

feat: PRT - adding metric to check number of websocket connections active at any given time

---

x/dualstaking/client/cli/tx_delegate.go
x/pairing/client/cli/tx_unstake_provider.go

Closes: #XXXX
This PR fixes a bug in the `unstake-provider` CLI in which providers could not unstake due to "invalid shares amount". The problem was with the `GetValidator()` helper function that is supposed to get a validator which the provider is delegated to, but didn't do it (wrong use of staking module query).
---
I have...
I have...

fix: faulty GetValidator helper function in Unstake CLI

---

protocol/chainlib/chainproxy/rpcInterfaceMessages/jsonRPCMessage.go
protocol/chainlib/chainproxy/rpcInterfaceMessages/tendermintRPCMessage.go
protocol/rpcconsumer/rpcconsumer_server.go
scripts/automation_scripts/pure_proxy.py

Closes: #XXXX
---
I have...
I have...

fix: PRT - fixing tendermint node error parser

---

app/app.go
app/upgrades/empty_upgrades.go
x/protocol/module.go
x/protocol/types/params.go

Closes: #XXXX
---
I have...
I have...

feat: CNS-v4.1.0-upgrade

---

protocol/chainlib/jsonRPC.go
protocol/chainlib/node_error_handler.go
protocol/chainlib/tendermintRPC.go

Closes: #XXXX
---
I have...
I have...

feat: PRT - fix node error handling on error codes 300+ / 200 -

---

protocol/chainlib/jsonRPC_test.go

This PR adds two new tests:
1. `TestJsonRPC_SpecUpdateWithAddons` - To test that the add-ons policy stays the same after a spec update
2. `TestJsonRPC_SpecUpdateWithExtensions` - To test that the extensions policy stays the same after a spec update

test: PRT: Add tests for addons and extensions after spec update

---

cookbook/specs/tendermint.json
protocol/lavaprotocol/request_builder.go

The discrepancy we found was in the in the log field of the tendermint's object called `ResponseDeliverTx` which is part of the `block_results` , `tx` and `broadcast_tx_commit` queries.
The discrepancy is in the timestamp, most likely because of different time zones. 
Our hypothesis is that the log field is no coming from on-chain data, and being calculated on spot. 
Adding a timestamp to it results in discrepancy in the results.

fix: PRT - tendermintrpc spec update - non deterministic queries

---

protocol/rpcprovider/rpcprovider_server.go
x/spec/keeper/spec_test.go

Closes: #XXXX
---
I have...
I have...

feat: CNS-autosort-spec-test

---

cookbook/specs/solana.json
protocol/chainlib/base_chain_parser.go

Closes: #XXXX
Added subscription APIs and modified the protocol code
---
I have...
I have...

chore: Solana Subscription APIs

---

protocol/chainlib/base_chain_parser.go
protocol/chainlib/grpc_test.go
protocol/chainlib/jsonRPC_test.go
protocol/chainlib/rest.go
protocol/chainlib/rest_test.go
protocol/chainlib/tendermintRPC_test.go
protocol/common/cobra_common.go
protocol/lavasession/consumer_session_manager.go
protocol/provideroptimizer/selection_weight.go
protocol/rpcconsumer/rpcconsumer.go
protocol/rpcprovider/rpcprovider.go

* adds a change in the functionality of specification API definitions, now APIs are allowed by default and need to be specifically blocked instead of only passing defined APIs, this allows easier integration of new chains and services
* solves a race in the consumer (double read locks)
---
I have...
I have...

feat: remove spec requirement to contain all apis

---

x/pairing/client/cli/query_effective_policy.go

Closes: #XXXX
---
I have...
I have...

fix: effective policy cmd argument parsing

---

protocol/common/cobra_common.go
protocol/rpcconsumer/rpcconsumer.go
protocol/rpcconsumer/rpcconsumer_server.go
protocol/statetracker/consumer_state_tracker.go

Closes: #XXXX
---
I have...
I have...

feat: PRT - DR flag now takes effecwt in  sendDataReliabilityRelayIfApplicable

---

protocol/lavasession/single_consumer_session.go

Closes: #XXXX
---
I have...
I have...

chore: PRT - fix spammy qos calc issue

---

specs/mainnet-1/specs/arbitrum.json

Closes: #XXXX
---
I have...
I have...

feat: add arbitrum trace apis

---

protocol/chainlib/rest.go
scripts/pre_setups/init_lava_only_with_node.sh

Closes: #XXXX
---
I have...
I have...

fix: PRT - fixing rest APIs that require event parsing such as txs returning HTML body.

---

x/rewards/keeper/iprpc.go
x/rewards/keeper/providers.go
x/rewards/keeper/providers_test.go
x/subscription/README.md
x/subscription/keeper/cu_tracker.go
x/subscription/keeper/grpc_query_estimated_rewards.go
x/subscription/types/expected_keepers.go

Closes: #XXXX
The estimate rewards query uses the payment events to get the estimation for the providers rewards. The event emitted the provider's part only, leading to lower estimations of the provider's total rewards. Now, the query returns the total estimated reward before its division between the providers and its delegators.
Also, I changed the "recommended block" to always be the last IPRPC distribution block (and updated README)
---
I have...
I have...

fix: estimate rewards query returns wrong estimations

---

x/spec/keeper/spec_test.go
x/spec/types/combinable.go

Closes: #XXXX
Added a small fix to the spec-add proposal mechanism that will allow specs with multiple Subscribe and Unsubscribe parse directives to be added to the chain. This was needed because Solana has multiple subscription APIs.
---
I have...
I have...

fix: handle multiple subscribe parse directives in spec-add

---

go.mod

See https://go.dev/doc/toolchain#version and https://github.com/lavanet/lava/security/code-scanning/tools/CodeQL/status/configurations/automatic/b56e7b9b62399faea59c45e7aba6c1da3b91f6b87643b640a033ac5c72b73b8b

chore: PRT - Update go version to match toolchain rule

---

protocol/lavaprotocol/request_builder.go
protocol/lavasession/consumer_types.go

Closes: #XXXX
fixed a minor issue in the QoS excellence report sent to the node
---
I have...
I have...

fix: invalid QoS excellence report to the node

---

protocol/monitoring/alerting.go
protocol/monitoring/health.go
protocol/monitoring/health_cmd.go
protocol/monitoring/health_results.go
protocol/monitoring/telegram_alerting.go
protocol/monitoring/telegram_alerting_test.go

Closes: #XXXX
---
I have...
I have...

feat: add telegram bot to lavap health

---

specs/mainnet-1/specs/filecoin.json

Closes: #XXXX
---
I have...
I have...

fix: add ChainNotify as WS API in FileCoin spec

---

app/app.go
app/upgrades/empty_upgrades.go
x/epochstorage/keeper/keeper.go
x/epochstorage/keeper/migrations.go
x/epochstorage/keeper/provider_metadata.go
x/epochstorage/module.go
x/epochstorage/types/provider_metdata.go
x/pairing/keeper/msg_server_stake_provider_test.go
x/pairing/keeper/staking.go
x/pairing/types/expected_keepers.go

Closes: #XXXX
Make sure the same vault can't stake twice with different operator address
---
I have...
I have...

fix: vault double stake bug

---

protocol/lavasession/consumer_session_manager.go
protocol/lavasession/consumer_session_manager_test.go
protocol/lavasession/consumer_types.go
protocol/rpcconsumer/rpcconsumer_server.go
scripts/init_chain.sh
scripts/pre_setups/init_lava_only_with_node_three_providers.sh
scripts/useful_commands.sh

Closes: #XXXX
---
I have...
I have...

fix: PRT - fix reconnect attempt on retry from blocked providers

---

specs/mainnet-1/specs/ripple.json

Closes: #XXXX
---
I have...
I have...

feat: PRT - ripple spec

---

specs/mainnet-1/specs/stellar.json

Closes: -
Added stellar specs
---
I have...
I have...

feat: FB added stellar specs

---

scripts/useful_commands.sh

yq is redundant we can use only jq, also there is a strange error if we have already installed yq with `apt install`, which is confusing

feat: use jq instead of yq
