- app/app.go
- app/upgrades/empty_upgrades.go
added an upgrade plan for version 0.4.3
> added upgrade plan

- Readme.md
> Update Readme with fixed version of GO

- cookbook/spec_add_polygon.json
> CNS-164 fixed typo in polygon spec name

- app/app.go
- app/upgrades/empty_upgrades.go
> add upgrade plan

- .github/workflows/e2e.yml
Adds retry to ignite chain build
ignite chain build fails randomly sometimes
Attempt to build 3 times before failing 
> PRT-177 Add retry for ignite build

- .github/workflows/e2e.yml
Fix the line spacing in e2e.yml that causes the actions to fail like on https://github.com/lavanet/lava/actions/runs/3951648249
Causes actions to fail because of syntax error
No more syntax error
> PRT-290 Fix line spacing in e2e.yml

- .github/workflows/e2e.yml
> PRT-299 Add timeout to retry

- testutil/e2e/e2e.go
> PRT-350 Gracefully shutdown providers and gateways

- .github/workflows/e2e.yml
- cmd/lavad/main.go
- relayer/chainproxy/connector.go
- relayer/chainproxy/connector_test.go
- relayer/chainproxy/grpc.go
- relayer/chainproxy/jsonRPC.go
- relayer/chainproxy/tendermintRPC.go
- relayer/test_client.go
adding and removing clients as the provider gets heavier usage 
constant number of clients when starting
adding and removing clients as the provider gets heavier usage 
added unit tests and ran them 
> PRT-343 reach by default to maximum number of connections available 

- cookbook/spec_add_polygon.json
- relayer/test_client.go
- relayer/testclients/polygon_tests.go
Add Polygon ifaces to spec
Add tests for Polygon ifaces to spec
Also fix Starnet's tests (port number)
> CNS-24 add polygon ifaces to spec

- .github/workflows/e2e.yml
> PRT-366 Print logs even if e2e fails

- app/app.go
- app/upgrades/empty_upgrades.go
> CNS - upgrade plan for v0.4.6

- .github/workflows/e2e.yml
- testutil/e2e/allowedErrorList.go
- testutil/e2e/e2e.go
> PRT-205 Add GRPC Tests to E2E

- cmd/lavad/main.go
> Fix cmdRPCProvider flag typo

- .github/workflows/e2e.yml
- relayer/chainproxy/grpc.go
Remove continue-on-error in E2E which makes failing tests pass.
> PRT-424 Remove continue-on-error in E2E

- app/app.go
- app/upgrades/v0_5_1/upgrade.go
- x/epochstorage/keeper/params.go
> CNS-upgrade plan 0.5.1

- protocol/chainlib/common.go
- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- protocol/chainlib/tendermintRPC.go
- relayer/chainproxy/chainproxy.go
- relayer/chainproxy/jsonRPC.go
- relayer/chainproxy/rest.go
- relayer/chainproxy/tendermintRPC.go
> PRT-438 Add dapp id to all interfaces

- app/upgrades/v0_5_2/upgrade.go
include the upgrade plan 0.5.0, 0.5.1
> update upgrade plan to 0.5.2

- config.yml
- cookbook/spec_add_aptos.json
- cookbook/spec_add_cosmoshub.json
- cookbook/spec_add_ethereum.json
- cookbook/spec_add_fantom.json
- cookbook/spec_add_juno.json
- cookbook/spec_add_lava.json
- cookbook/spec_add_osmosis.json
- cookbook/spec_add_polygon.json
- cookbook/spec_add_starknet.json
- cookbook/spec_add_terra.json
- go.mod
- go.sum
- scripts/init_chain_commands.sh
- scripts/init_e2e.sh
- scripts/init_e2e_lava_over_lava.sh
- scripts/init_lava_over_lava.sh
- scripts/pre_setups/init_chain_commands_one_provider.sh
- scripts/pre_setups/init_gth_only.sh
- scripts/pre_setups/init_lava_grpc.sh
- scripts/pre_setups/init_osmosis_test.sh
- scripts/scripts_archive/test_unstake_provider.sh
> minstake is now like the testnet

- cookbook/spec_add_arbitrum.json
- cookbook/spec_add_celo.json
> CNS-fixed minstake for CELO and ARB specs

- x/spec/types/spec.go
Rebuilding tree this time on `release` branch
> Add validation to the spec parameters (#304)

- app/app.go
- app/upgrades/empty_upgrades.go
Rebuilding tree this time on release branch
> Add upgrade plan 0.6.0 (#305)

- relayer/chainproxy/tendermintRPC.go
> Remove mandatory flag from tendermint

- app/app.go
- app/upgrades/empty_upgrades.go
> Cns upgrade plan 0.6.0 rc3

- relayer/server.go
feature
We are missing data inside one of the error messages
Added missing commet
> Add comment for epoch block

- protocol/rpcconsumer/README.md
> Create README for RPCConsumer

- app/app.go
- app/upgrades/empty_upgrades.go
> Cns upgrade 0.6.1

- cookbook/spec_add_base.json
- scripts/init_chain_commands.sh
- scripts/setup_providers.sh
> CNS-303-add-base-blockchain-spec

- cookbook/README.md
- [ V ] Commit message follows the Contribution Guidelines
- [ V ] Tests ran locally and added/modified if needed
- [ V ] Docs have been added/updated, if applicable
- [ V ] If applicable - JIRA ticket ID was added
docs update
no README for specs
added README for specs (under "cookbook")
> CNS-284: create a spec readme explaining all the fields

- cookbook/README.md
Please check if the PR fulfills these requirements
[ V ] Commit message follows the Contribution Guidelines
[ V ] Tests ran locally and added/modified if needed
[ V ] Docs have been added/updated, if applicable
[ V ] If applicable - JIRA ticket ID was added
What kind of change does this PR introduce? (Bug fix, feature, unit tests, docs update, ...)
docs update
What is the current behavior? (You can also link to an open issue here)
spec README not complete
What is the new behavior (if this is a feature change)?
spec README is complete
Please describe what manual tests you ran, if applicable
Other information:
> CNS-321: updated spec README

- protocol/chainlib/chainproxy/rpcInterfaceMessages/tendermintRPCMessage.go
- protocol/chainlib/chainproxy/rpcInterfaceMessages/tendermintRPCMessage_test.go
bug fix
error in convert tendermint msg
fix the issue
> Fix bug in convert tendermint msg

- x/projects/keeper/project.go
> fixed error printing on handled legacy code

- cmd/lavad/cmd/root.go
This small PR adds support for snapshot keeping for state sync
> CNS-296: add support for snapshot keeping to enable state sync

- common/fixation_entry.go
- common/fixation_entry_test.go
- common/types/errors.go
- x/plans/keeper/plan.go
- x/plans/keeper/plan_test.go
- x/projects/keeper/creation.go
- x/projects/keeper/msg_server_set_project_policy.go
- x/projects/keeper/project.go
- x/subscription/types/expected_keepers.go
> Revert "CNS-368: fixation: improve API for GetEntry,FindEntry,PutEntry"

- protocol/rpcprovider/rpcprovider.go
- x/pairing/client/cli/tx.go
- x/pairing/client/cli/tx_modify_provider.go
- x/pairing/keeper/staking.go
> CNS-419-cli-tooling-improvements-provider-modify

- cmd/lavad/main.go
- protocol/chaintracker/chain_tracker.go
- protocol/rpcprovider/testing.go
- protocol/statetracker/events.go
- x/pairing/client/cli/query_account_info.go
- x/pairing/client/cli/query_clients.go
- x/pairing/client/cli/query_get_pairing.go
- x/pairing/client/cli/query_providers.go
- x/pairing/client/cli/query_static_providers_list.go
- x/pairing/client/cli/query_user_entry.go
- x/pairing/client/cli/query_verify_pairing.go
- x/plans/client/cli/query_info.go
- x/plans/client/cli/query_list.go
- x/projects/client/cli/query_developer.go
- x/projects/client/cli/query_info.go
- x/spec/client/cli/query_show_all_chains.go
- x/spec/client/cli/query_show_chain_info.go
- x/subscription/client/cli/query_current.go
also support --height on generated commands
> PRT-645-implement-a-tool-to-identify-events-for-account

- .github/workflows/network-upgrades-tag-populate.yml
This automation will listen to newly created tags on the main branch, to populate the list in the pipeline.
> DO-1304 Add trigger on tags to populate the Network Upgrades CI

- cookbook/specs/spec_add_arbitrum.json
- cookbook/specs/spec_add_avalanche.json
- cookbook/specs/spec_add_base.json
- cookbook/specs/spec_add_bsc.json
- cookbook/specs/spec_add_celo.json
- cookbook/specs/spec_add_cosmoshub.json
- cookbook/specs/spec_add_cosmossdk.json
- cookbook/specs/spec_add_ethereum.json
- cookbook/specs/spec_add_fantom.json
- cookbook/specs/spec_add_optimism.json
- cookbook/specs/spec_add_polygon.json
- cookbook/specs/spec_add_solana.json
- cookbook/specs/spec_add_starknet.json
- scripts/updateSpecsCu.py
wrote a python script to update ETH-based chains' CU and updated the specs. Note that I've mistakenly did it on CNS-400 design task instead of the actual CNS-66 task @SeanZoR
> CNS-66: Update CU's for EVM family 

- Dockerfile
- Makefile
- docker/README.md
- docker/docker-compose.yml
- docker/start_node.sh
Follow docker/README.md to test and try it out.
> CNS-409 update docker image for lava node

- Readme.md
- scripts/lavad_auto_completion_install.sh
Added @oren-lava AutoComplete to Repo !
> Update Readme with Autocomplete Gist Link

- cookbook/projects/example_project_keys.yml
- proto/subscription/query.proto
- x/projects/keeper/project.go
- x/subscription/client/cli/query.go
- x/subscription/client/cli/query_list_projects.go
- x/subscription/keeper/grpc_query_list_projects.go
- x/subscription/keeper/msg_server_add_project.go
- x/subscription/keeper/subscription_test.go
- x/subscription/types/expected_keepers.go
- x/subscription/types/query.pb.go
- x/subscription/types/query.pb.gw.go
This query gets a subscription address and returns all the subscription's projects
> CNS-450 implemented getting subscription's projects

- x/projects/keeper/project_test.go
- x/subscription/keeper/subscription_test.go
Subscriptions can add/delete projects; Projects can add/delete keys;
Double-nested delete happens the user deletes a project and then in the same
epoch also deletes a key (and also the reverse: first key then project, in
the same epoch).
Double-nested delete also happens when the subscription expires in the same
epoch that a user deleted a project (of that subscription).
Add tests that verify that these events are handled correctly without errors
or a panic (specifically, due to stray timer).
> CNS-487 test double nested deletion

- protocol/chainlib/chainproxy/rpcInterfaceMessages/jsonRPCMessage.go
- protocol/chainlib/node_error_handler.go
- protocol/chaintracker/chain_tracker.go
- protocol/common/errors.go
- scripts/pre_setups/init_solana_only.sh
THis PR add suggestion if connecting to the node fails because of the context deadline
> [PRT-754] Add suggestion if context deadline

- ecosystem/lava-sdk/README.md
Improve Lava Sdk doc to include badge server and also explanation why someone should use badge server over private keys
> Improve SDK doc to include badge

- scripts/init_chain_commands.sh
Description:
Init chain command script is missing wait time between proposals 
Fix:
Increase wait time to 4s
> Fix init chain commands script

- protocol/metrics/metricsService.go
As part of the more secure communication between our services, we must add the option to specify the Authorization Header.
> GROW-1080 Add Authorization Header option for the metrics relays.

- ecosystem/lavavisor/cmd/create-service.go
* added parallel-connection flag
* service file formatting
* created flag for creating link for service files to system path
> Lavavisor service file fixes

- ecosystem/lavavisor/cmd/create-service.go
- ecosystem/lavavisor/pkg/process/version_monitor.go
upgraded binary switch tested with --auto-download
> Lavavisor staging version switch fix

- cmd/lavavisor/README.md
readme updated according to latest changes
> lavavisor readme update

- cookbook/specs/spec_add_sqdsubgraph.json
- protocol/chainlib/chainproxy/rpcInterfaceMessages/jsonRPCMessage.go
- protocol/lavasession/provider_session_manager.go
one parsing empty data buffer out of range
one when getting a session error with badges triggering null ref
> BUG-fix-panics

- protocol/chainlib/grpc.go
- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- protocol/chainlib/tendermintRPC.go
- protocol/common/conf.go
- protocol/common/endpoints.go
- protocol/lavasession/consumer_session_manager.go
- protocol/rpcconsumer/rpcconsumer_server.go
- protocol/rpcprovider/rpcprovider_server.go
- protocol/rpcprovider/testing.go
- x/protocol/types/params.go
added provider address to consumer responses, and provider version to probes
> PRT add informative headers to responses

- .github/workflows/network-upgrades-tag-populate.yml
> Network upgrade deployments update population tags location

- x/rewards/keeper/providers.go
Send funds of validators participation to the distribution pool (or allocation pool in edge case) instead of fee collector
> CNS-797: fix participation issue

- testutil/keeper/pairing.go
- x/conflict/types/params.go
- x/epochstorage/keeper/epoch_details.go
- x/epochstorage/keeper/fixated_params.go
- x/pairing/keeper/params.go
- x/spec/types/params.go
params verifications fixes confirmed with @omerlavanet
> CNS-801: params verifications

- cookbook/specs/spec_add_axelar.json
- cookbook/specs/spec_add_cosmossdk.json
- cookbook/specs/spec_add_ethereum.json
- cookbook/specs/spec_add_solana.json
- cookbook/specs/spec_add_starknet.json
> fixing determinism for all transactions for data reliability verifications 

- proto/lavanet/lava/rewards/query.proto
- scripts/cli_test.sh
- testutil/common/tester.go
- x/rewards/client/cli/query.go
- x/rewards/client/cli/query_provider_reward.go
- x/rewards/keeper/base_pay.go
- x/rewards/keeper/grpc_query_provider_reward.go
- x/rewards/types/query.pb.go
- x/rewards/types/query.pb.gw.go
https://lavanet.atlassian.net/browse/CNS-822
> CNS-822: Add support for provider-reward query

- cookbook/specs/spec_add_blast.json
**Where are you in the process of adding the spec?**
I’ve completed drafting the spec, but I’m looking forward to adding more integrated functionalities to enhance its capabilities further.
**Why did you choose to add this spec to Lava?**
I’m planning to integrate this spec into my `create-blast-dapp` project, especially if I win in the ongoing competition. I aim for it to support the basic operational features of the Blast chain, ensuring smooth functionality.
**What help do you need?**
So far, the documentation has been incredibly clear and helpful, so I haven’t encountered any confusion. Everything seems straightforward.
**Provide some links to the Blast (Docs or whitepaper) for reference**
Blast Website: https://blast.io/
Documentation: [About Blast - Blast Developer …
> Add specs: Blast Sepolia

- cookbook/specs/spec_add_cosmossdk.json
- cookbook/specs/spec_add_evmos.json
- scripts/pre_setups/init_evmos_only_with_node.sh
> PRT-Adding-gas-verifications-to-cosmos

- x/pairing/keeper/epoch_payments.go
- x/pairing/keeper/msg_server_relay_payment.go
- x/pairing/keeper/msg_server_relay_payment_test.go
- x/pairing/keeper/provider_payment_storage.go
- x/pairing/keeper/unique_payment_storage_client_provider.go
to save on gas and improve performance, I've added cache store support for the epoch payments mechanism
> CNS-929: add cache store to epoch payments

- cookbook/specs/spec_add_polygon.json
Testing command was successful:
```
./scripts/test_spec_full.sh cookbook/specs/spec_add_polygon.json jsonrpc https://polygon-rpc.com jsonrpc https://polygon-mumbai-bor-rpc.publicnode.com jsonrpc https://rpc-amoy.polygon.technology
```
> feat: Update Polygon spec to include new Amoy testnet

- x/dualstaking/keeper/delegate_test.go
- x/dualstaking/keeper/delegator_reward.go
- x/dualstaking/keeper/helpers_test.go
- x/epochstorage/types/types.go
> feat: Revert CNS-945-remove-frozen-from-epochstorage

- cookbook/specs/ethereum.json
- protocol/chainlib/consumer_websocket_manager.go
- protocol/chainlib/consumer_ws_subscription_manager.go
- protocol/chainlib/consumer_ws_subscription_manager_test.go
- protocol/chainlib/jsonRPC.go
- protocol/common/errors.go
- protocol/common/strings.go
- protocol/rpcconsumer/rpcconsumer.go
- scripts/init_chain.sh
Closes: #XXXX
---
I have...
I have...
> fix: PRT-1178: Subscription phase 1 unsubscribe fix

- .github/workflows/release.yml
Closes: #XXXX
---
I have...
I have...
> chore: Fix go-releaser-crosscompile

- utils/cli/multisend.go
Closes: #XXXX
---
I have...
I have...
> fix: CNS-multi-send-cli-fix

- utils/cli/multisend.go
Closes: #XXXX
---
I have...
I have...
> fix: Cns multi send cli fix 2

- utils/cli/multisend.go
Closes: #XXXX
---
I have...
I have...
> fix: CNS-multi-send-cli-fix-3

- app/app.go
- app/upgrades/empty_upgrades.go
- x/subscription/keeper/grpc_query_estimated_rewards.go
- x/subscription/keeper/grpc_query_estimated_validator_rewards.go
Closes: #XXXX
---
I have...
I have...
> fix: CNS-fix-reward-query

- protocol/rpcprovider/rpcprovider_server.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - adding logs to error for requested block mismatch

- config/provider_examples/lava_example_archive_methodroute.yml
- protocol/chainlib/chain_router.go
- protocol/chainlib/chain_router_test.go
- protocol/chainlib/extensionslib/extension_parser.go
- protocol/common/endpoints.go
- protocol/lavasession/router_key.go
Closes: #XXXX
---
I have...
I have...
> feat: support provider method routes

- protocol/chainlib/protocol_message.go
- protocol/common/endpoints.go
- protocol/lavasession/consumer_session_manager.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding debug headers and fixing nil deref on response nil

- app/app.go
- app/upgrades/empty_upgrades.go
- x/protocol/module.go
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: CNS-upgrade-v3.0.1

- protocol/chainlib/base_chain_parser.go
- protocol/chainlib/consumer_websocket_manager.go
- protocol/chainlib/rest.go
- protocol/chainlib/rest_test.go
Closes: #XXXX
---
I have...
I have...
> feat: reduce spam logs on consumer side

- protocol/common/cobra_common.go
- protocol/rpcconsumer/relay_processor.go
- protocol/rpcconsumer/relay_processor_test.go
- protocol/rpcconsumer/rpcconsumer.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - add relay retry atttempts flag

- utils/cli/multisend.go
Closes: #XXXX
Small fix to total-gas query to avoid near-infinite loop.
---
I have...
I have...
> fix: total gas query: check sequence

- protocol/common/endpoints.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding api requested to returned headers

- cookbook/specs/fantom.json
Closes: #XXXX
---
I have...
I have...
> feat: add fantom trace addon

- cookbook/specs/lava.json
- cookbook/specs/lava_mainnet.json
Closes: #XXXX
---
I have...
I have...
> feat: CNS-lava-spec-add-identity

- protocol/rpcconsumer/consumer_relay_state_machine.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix race condition on state machine stateful state

- protocol/integration/protocol_test.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - add archive integration tests.

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - increase protocol version.

- scripts/test/init_payment_e2e.sh
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix race in payments e2e

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - increase protocol version 3-1-7

- protocol/provideroptimizer/provider_optimizer_test.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - optimizer test fix

- protocol/common/endpoints.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding stateful api header for hanging relays

- protocol/chainlib/consumer_websocket_manager.go
- protocol/chainlib/consumer_ws_subscription_manager_test.go
- protocol/common/cobra_common.go
- protocol/common/return_errors.go
- protocol/rpcconsumer/rpcconsumer.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - add rate limit to ws

- protocol/chainlib/consumer_websocket_manager.go
- protocol/metrics/rpcconsumerlogs.go
…ld reach the subscription flow and spam the logger with api mismatches
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix ws issue reaching subscription flow from regular relay flow 

- x/pairing/client/cli/tx_modify_provider.go
Closes: #XXXX
Fixed small bug in the `modify-provider` CLI code.
---
I have...
I have...
> fix: fix modify-provider validator flag

- .github/workflows/release.yml
Closes: #XXXX
---
I have...
I have...
> feat: Add support for experimental releases

- protocol/statetracker/updaters/epoch_updater.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - validate epoch updater is not already stored

- .github/workflows/release.yml
Closes: #XXXX
---
I have...
I have...
> feat: Fix publish release workflow step

- protocol/chainlib/base_chain_parser.go
- protocol/chainlib/extensionslib/extension_parser.go
- protocol/chainlib/grpc.go
- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- protocol/chainlib/tendermintRPC.go
> fix: PRT - Fix the bug that prevented existing addons to be enabled after spec  update

- app/app.go
- app/upgrades/empty_upgrades.go
- x/protocol/module.go
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: cns-v3.2.0 upgrade handler

- .github/workflows/release.yml
Closes: #XXXX
---
I have...
I have...
> ci: workflow trigger

- protocol/statetracker/updaters/pairing_updater.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fixing total stake amount taking only stake size into consideration

- x/rewards/keeper/base_pay.go
- x/rewards/keeper/helpers_test.go
change the spec name in the tests to create the case where the specs names are the same at the start
Closes: #XXXX
---
I have...
I have...
> fix: CNS-fix-iprpc-cu-iterator

- x/pairing/keeper/msg_server_relay_payment.go
Closes: #XXXX
---
I have...
I have...
> feat: CNS-add-report-event-data-to-relay-payment

- scripts/automation_scripts/update_cosmos_spec_from_grpc.py
Closes: #XXXX
---
I have...
I have...
> feat: Adapt cosmos spec updater spec to support Evmos

- cookbook/specs/lava.json
- cookbook/specs/lava_mainnet.json
- scripts/automation_scripts/update_cosmos_spec_from_grpc.py
Closes: #XXXX
---
I have...
I have...
> feat: CNS-v4-specs

- x/dualstaking/client/cli/query_delegator_rewards.go
- x/dualstaking/keeper/grpc_query_delegator_rewards.go
… providers
Closes: #XXXX
In this PR I fixed a bug in the `delegator-rewards` query which didn't show claimable rewards of providers the delegator is not currently delegated to. Basic flow to reproduce:
1. delegate to a provider
2. get rewards
3. redelegate from provider and not claim your rewards
This makes the query not print all the rewards and worse than that, since the `claim-rewards` TX uses the `delegator-rewards` query to get the claimable rewards, the missing rewards could not be claimed.
---
I have...
your handle next to the items reviewed if you only …
> fix: delegator rewards query bug

- protocol/chainlib/grpc.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - added the error so we can solve problems for users

- cookbook/specs/celestia.json
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding missing API's to celestia

- protocol/monitoring/chain_heights.go
Closes: #XXXX
---
I have...
I have...
> fix: v3 paths in main

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - increase version to 4.1.1

- x/pairing/client/cli/query_account_info.go
Closes: #XXXX
---
I have...
I have...
> feat: CNS-account-info-fix

- go.mod
- utils/sigs/sigs.go
- x/conflict/types/relay_finalization.go
- x/pairing/types/relay_exchange.go
- x/pairing/types/relay_exchange_test.go
- x/pairing/types/relay_session.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix seg fault on raced bytes array

- cookbook/specs/evmos.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT - remove gas verification for abci_query

- cookbook/specs/fvm.json
- cookbook/specs/movement.json
Closes: #XXXX
---
I have...
I have...
> feat: CNS-fvm-update

- cookbook/specs/celestia.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT update celestia block time

- x/pairing/client/cli/tx_distribute_provider_stake.go
fix the errors
Closes: #XXXX
---
I have...
I have...
> fix: CNS-distribution-cli-fixes

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - increase protocol version

- x/spec/keeper/spec_test.go
Closes: #XXXX
---
I have...
I have...
> fix: CNS-spec-test-fix

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - increase target version to 4.1.3

- cookbook/specs/celestia.json
- scripts/pre_setups/init_celestia_only_with_node.sh
Closes: #XXXX
---
I have...
I have...
> feat: PRT - Add gas verification for celestia

- protocol/rpcconsumer/relay_state.go
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - archive retry attempt on second relay regardless of node error

- ecosystem/lavavisor/pkg/state/lavavisor_state_tracker.go
- protocol/badgegenerator/tracker.go
- protocol/badgeserver/tracker.go
- protocol/rpcconsumer/custom_transport.go
- protocol/rpcconsumer/rpcconsumer.go
- protocol/rpcprovider/rpcprovider.go
- protocol/statetracker/consumer_state_tracker.go
- protocol/statetracker/events.go
- protocol/statetracker/provider_state_tracker.go
- protocol/statetracker/state_tracker.go
- protocol/statetracker/updaters/event_tracker.go
- protocol/statetracker/updaters/provider_freeze_jail_updater.go
- protocol/statetracker/updaters/provider_freeze_jail_updater_mocks.go
- protocol/statetracker/updaters/state_query.go
Closes: #XXXX
---
I have...
I have...
> chore: refactor state query access

- config/provider_examples/lava_example_archive_method_route.yml
- cookbook/projects/policy_all_chains_with_extension.yml
- scripts/init_chain_commands.sh
- scripts/test/httpServer.py
Closes: #XXXX
---
I have...
I have...
> chore: added utils to test method routing

- protocol/common/cobra_common.go
- protocol/lavasession/consumer_session_manager.go
- protocol/metrics/consumer_metrics_manager.go
- protocol/rpcconsumer/rpcconsumer.go
Adds periodic probing for providers for metrics.
> feat: FB - Added periodic provider probe

- scripts/useful_commands.sh
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix spec issues

- protocol/lavasession/consumer_session_manager.go
- protocol/metrics/consumer_metrics_manager.go
Added provider_endpoint to lava_consumer_latest_provider_block metric
> feat: FB - Added provider_endpoint to lava_consumer_latest_provider_block

- specs/mainnet-1/specs/starknet.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT-fix-strk-ws-spec

- ecosystem/cache/handlers.go
- ecosystem/cache/server.go
- go.mod
- go.sum
- protocol/lavaprotocol/relay_retries_manager.go
- protocol/monitoring/alerting.go
- protocol/provideroptimizer/provider_optimizer.go
- protocol/rpcconsumer/consumer_consistency.go
- protocol/statetracker/updaters/state_query.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - upgrade ristretto version

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - 4.2.2

- cmd/lavap/main.go
- ecosystem/cache_populator/command.go
- ecosystem/cache_populator/test_config.json
Closes: #XXXX
---
I have...
I have...
> feat: PRT - golang cache populator cmd

- specs/mainnet-1/specs/ethereum.json
- testutil/e2e/protocolE2E.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding trace methods to ethereum

- protocol/metrics/consumer_metrics_manager.go
* Added provider_endpoint to qos and qos_excellence metrics
> feat: FB add provider endpoint to qos metrics

- cmd/lavad/Dockerfile
- cmd/lavap/Dockerfile
Closes: #XXXX
---
I have...
I have...
> fix: Fix docker build step

- cmd/lavad/main.go
- utils/cli/multicheck.go
- x/subscription/client/cli/query.go
- x/subscription/client/cli/query_estimated_rewards.go
Closes: #XXXX
---
I have...
I have...
> feat: add pool-rewards-breakdown command

- protocol/metrics/consumer_metrics_manager.go
- protocol/metrics/provider_metrics_manager.go
- protocol/metrics/relays_monitor_aggregator.go
Added new metric, lava_consumer_overall_health_breakdown which shows the overall health of a chain based on chain and api interface
> feat: Added lava_consumer_overall_health_breakdown metric

- x/dualstaking/keeper/delegator_reward.go
Closes: #XXXX
Adding a 100% commission edge case to delegator reward to avoid rounding errors
---
I have...
I have...
> fix: dealing with 100% commission

- config/provider_examples/provider_example_cookbook/avalanche_provider_auto_complete.yml
- config/provider_examples/provider_example_cookbook/avalanche_provider_with_internal_paths.yml
- config/provider_examples/provider_example_cookbook/eth_provider_with_archive_debug_trace.yml
- config/provider_examples/provider_example_cookbook/solana_config.yml
- config/provider_examples/provider_example_cookbook/starknet_auto_complete_with_addon.yml
- config/provider_examples/provider_example_cookbook/starknet_auto_complete_without_addons.yml
- config/provider_examples/provider_example_cookbook/starknet_example_full_internal_path.yml
- config/provider_examples/strk_addon_example_with_root.yml
- config/provider_examples/strk_addon_example_with_ws.yml
Closes: #XXXX
---
I have...
I have...
> chore: PRT - adding examples configurations for providers to use on mainnet.

- ecosystem/lavavisor/pkg/process/fetcher.go
Closes: #XXXX
---
I have...
I have...
> fix: Fixed to correct version GO 1.23.0

- protocol/chainlib/chain_router.go
- protocol/monitoring/health.go
- protocol/rpcconsumer/testing.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix health and test commands removing WS panic.

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - increase protocol version in main

- ecosystem/cache_populator/scripts/request_counter.py
Closes: #XXXX
---
I have...
I have...
> chore: PRT - add request counter for debugging the populator

- config/consumer_examples/lava_consumer_static_peers.yml
- config/provider_examples/lava_example2.yml
- protocol/integration/mocks.go
- protocol/lavasession/consumer_session_manager.go
- protocol/rpcconsumer/consumer_state_tracker_mock.go
- protocol/rpcconsumer/rpcconsumer.go
- protocol/statetracker/consumer_state_tracker.go
- protocol/statetracker/updaters/finalization_consensus_updater.go
- protocol/statetracker/updaters/pairing_updater.go
- protocol/statetracker/updaters/state_query.go
- scripts/pre_setups/init_lava_static_provider.sh
- scripts/test/init_payment_e2e.sh
- x/epochstorage/keeper/params.go
- x/pairing/keeper/pairing_next_epoch_time_block.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - Static provider bug fix

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - increase minimum version + protocol version to 4.2.8 / 4.2.1

- config/provider_examples/provider_example_cookbook/eth_provider_with_archive_debug_trace.yml
- protocol/chainlib/chain_router.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding a more indicative error for provider config

- app/app.go
- app/upgrades/empty_upgrades.go
- testutil/keeper/mock_keepers.go
- x/pairing/keeper/cu_tracker_test.go
- x/pairing/keeper/delegator_rewards_test.go
- x/pairing/keeper/grpc_query_provider_reputation.go
- x/pairing/keeper/migrations.go
- x/pairing/keeper/reputation.go
- x/pairing/module.go
Closes: #XXXX
---
I have...
I have...
> feat: CNS v5.0.0

- protocol/provideroptimizer/provider_optimizer_test.go
- utils/score/score_store_test.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix a statistical test failing over delta

- protocol/provideroptimizer/provider_optimizer_test.go
Closes: #XXXX
---
I have...
I have...
> test: PRT - add optimizer sync weighted test.

- scripts/init_chain_commands.sh
- x/dualstaking/keeper/migrations.go
Closes: #XXXX
---
I have...
I have...
> fix: CNS-fix-credit-migrator

- protocol/monitoring/telegram_alerting.go
- protocol/monitoring/telegram_alerting_test.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - git timestamp issue resolved v4 / v5

- protocol/provideroptimizer/provider_optimizer.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix a provider optimizer issue where PENDING/SAFE/FINALIZED were returning errors.

- protocol/chainlib/common.go
- protocol/common/timeout.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - reducing retry timeout to 1 second In order to increase stability

- specs/mainnet-1/specs/worldchain.json
> feat: added worldchain specs

- protocol/lavasession/consumer_session_manager.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - Add QOS reputation for static providers.

- specs/testnet-2/specs/bera.json
Closes: #XXXX
DO NOT MERGE UNTIL BLOCK TIME IS CONFIRMED
---
I have...
I have...
> chore: add spec Berachain Mainnet

- protocol/chainlib/chainproxy/rpcclient/json.go
- protocol/chainlib/common.go
- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- scripts/pre_setups/init_btc_only_with_node.sh
Closes: #XXXX
---
I have...
I have...
> feat: PRT - add UTXO support on protocol side. do not omit empty nil errors / results.

- app/app.go
- app/upgrades/empty_upgrades.go
- scripts/init_chain_commands.sh
Closes: #XXXX
---
I have...
I have...
> feat: CNS v5.1.0

- protocol/provideroptimizer/provider_optimizer_test.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - adding a auto adjustment tier test to provider optimizer.

- scripts/pre_setups/init_fvm_only_with_node.sh
- specs/mainnet-1/specs/filecoin.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix fvm spec

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: PRT - increase protocol version 5.1.1

- protocol/chainlib/jsonRPC.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - Route eth call to archive

- x/protocol/module.go
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: increase protocol version to v5.2.0

- specs/mainnet-1/specs/litecoin.json
> feat: added litecoin specs

- specs/mainnet-1/specs/doge.json
> feat: added Doge specs

- specs/testnet-2/specs/sonic.json
Closes: #XXXX
Added Sonic (previously Fantom) spec. This will be a separate spec until Fantom is completely not supported
---
I have...
I have...
> feat: add sonic spec

- protocol/monitoring/alerting.go
- protocol/monitoring/telegram_alerting.go
Closes: #XXXX
---
I have...
I have...
> fix: telegram alerting tuning

- specs/mainnet-1/specs/tendermint.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT - hash parsing fix on Tendermintrpc

- specs/mainnet-1/specs/avalanche.json
Closes: #XXXX
---
I have...
I have...
> fix: PRT - add verification directive for Avalanche specs

- specs/mainnet-1/specs/lava-mainnet.json
- specs/testnet-2/specs/lava.json
Closes: #XXXX
---
I have...
I have...
> chore: update lava specs with new v5 apis

- x/pairing/keeper/msg_server_relay_payment.go
Closes: #XXXX
The timestamp trait was non deterministic. Fixed to make it use UTC and constant format.
---
I have...
I have...
> fix: reported provider event non-deterministic

- app/app.go
- specs/mainnet-1/specs/arbitrum.json
- specs/mainnet-1/specs/avalanche.json
- specs/mainnet-1/specs/base.json
- specs/mainnet-1/specs/blast.json
- specs/mainnet-1/specs/celo.json
- specs/mainnet-1/specs/ethereum.json
- specs/mainnet-1/specs/fantom.json
- specs/mainnet-1/specs/fuse.json
- specs/mainnet-1/specs/optimism.json
- specs/mainnet-1/specs/polygon.json
- specs/mainnet-1/specs/worldchain.json
- specs/testnet-2/specs/bsc.json
- specs/testnet-2/specs/sonic.json
- specs/undeployed/manta_pacific.json
- specs/undeployed/scroll.json
- specs/undeployed/zksync.json
Closes: #XXXX
---
I have...
I have...
> chore: align evm chains to 128 blocks pruning

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - protocol version upgrade for 5.2.1

- specs/mainnet-1/specs/tron.json
Closes: -
Added tron specs
---
I have...
I have...
> feat: add tron specs

- specs/mainnet-1/specs/ripple.json
Closes: -
---
I have...
I have...
> feat: :sparkles: FB - added ripple spec

- specs/mainnet-1/specs/movement.json
Closes: #XXXX
---
I have...
I have...
> fix: update movement mainnet spec

- ecosystem/lavavisor/pkg/process/fetcher.go
- ecosystem/lavavisor/pkg/process/fetcher_without_build.go
- protocol/chainlib/node_error_handler.go
- protocol/chainlib/node_error_handler_test.go
- protocol/monitoring/health.go
- protocol/rpcprovider/testing.go
- scripts/pre_setups/init_movement_only_with_node.sh
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> fix: PRT - fix rest provider client for movement

- protocol/rpcconsumer/README.md
Closes: #XXXX
---
I have...
I have...
> docs: Update README.md

- protocol/chainlib/base_chain_parser.go
- protocol/chainlib/protocol_message.go
- protocol/chainlib/protocol_message_test.go
- protocol/integration/protocol_test.go
- protocol/lavaprotocol/finalizationconsensus/finalization_consensus_test.go
- protocol/lavasession/consumer_session_manager.go
- protocol/lavasession/consumer_types.go
- protocol/qos/qos_manager.go
- protocol/qos/qos_mutator_degrade_availability.go
- protocol/rpcconsumer/consumer_relay_state_machine_test.go
- protocol/rpcconsumer/relay_processor.go
- protocol/rpcconsumer/relay_processor_test.go
- protocol/rpcconsumer/rpcconsumer_server.go
- protocol/rpcprovider/reliabilitymanager/reliability_manager_test.go
Closes: #XXXX
---
I have...
I have...
> feat: PRT - QOS - degrade availability on node errors

- protocol/lavasession/consumer_session_manager.go
- protocol/lavasession/consumer_session_manager_test.go
Closes: #XXXX
---
I have...
I have...
> fix: revert retry on blocked providers

- specs/mainnet-1/specs/stellar.json
* Added missing transactions API method
> feat: FB - Add missing transactions API call

- README.md
Closes: #XXXX
---
I have...
I have...
> feat: PRT - stellar spec

- x/conflict/types/codec.go
- x/dualstaking/types/codec.go
- x/pairing/types/codec.go
- x/projects/types/codec.go
- x/rewards/types/codec.go
- x/subscription/types/codec.go
Closes: #XXXX
---
I have...
I have...
> feat: Allow amino encoding support for lava TXs for Authz

- app/app.go
- app/upgrades/empty_upgrades.go
- x/protocol/module.go
- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> feat: upgrade version v5.3.0

- protocol/rpcprovider/rpcprovider.go
- specs/mainnet-1/specs/starknet.json
- utils/lavaslices/slices.go
- utils/lavaslices/slices_test.go
Closes: #XXXX
---
I have...
I have...
> fix: run verifications for generated urls

- protocol/metrics/consumer_metrics_manager.go
- protocol/metrics/rpcconsumer_logs.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
To add futher visibility to providers error rate, I added to prometheus metrics of protocol errors count per provider and chain, and total relays count per provider per chain. This will allow seeing the protocol error rate of providers
---
I have...
I have...
> feat: protocol errors and total relays per provider per chain metrics

- specs/mainnet-1/specs/bch.json
> feat: added bitcoin cash specs

- specs/mainnet-1/specs/avalanche.json
- specs/mainnet-1/specs/ethereum.json
- specs/mainnet-1/specs/tendermint.json
- specs/testnet-2/specs/bsc.json
- specs/testnet-2/specs/union.json
Closes: #XXXX
---
I have...
I have...
> chore: fix min stake to 5k

- specs/mainnet-1/specs/ripple.json
- specs/mainnet-1/specs/ton.json
Closes: #XXXX
---
I have...
I have...
> feat: PRT - TON spec.

- app/app.go
- app/upgrades/empty_upgrades.go
Closes: #XXXX
---
I have...
I have...
> chore: v5.4.0 upgrade handler

- protocol/lavasession/consumer_session_manager.go
- protocol/lavasession/consumer_session_manager_test.go
- protocol/lavasession/consumer_types.go
- protocol/rpcconsumer/consumer_relay_state_machine.go
- protocol/rpcconsumer/rpcconsumer_server.go
Closes: #XXXX
---
I have...
I have...
> chore: adding guid to all logs of relay

- protocol/chainlib/chain_fetcher.go
- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- protocol/chaintracker/chain_tracker.go
- protocol/lavasession/provider_types.go
- protocol/metrics/rpcconsumer_logs.go
- protocol/rpcconsumer/rpcconsumer_server.go
- protocol/rpcprovider/rpcprovider.go
- protocol/rpcprovider/rpcprovider_server.go
- protocol/statetracker/updaters/pairing_updater.go
Closes: Nothing
Update logging and tracking of request through consumer and provider
Added ability to specify name in the consumer's provider config for better readability
---
I have...
I have...
> fix: added logging functionality

- protocol/chainlib/jsonRPC.go
- protocol/chainlib/rest.go
- protocol/chaintracker/chain_tracker.go
- protocol/lavasession/consumer_types.go
- protocol/lavasession/single_provider_session.go
- protocol/metrics/rpcconsumer_logs.go
- protocol/rpcconsumer/rpcconsumer_server.go
- protocol/rpcprovider/rpcprovider_server.go
- utils/lavalog.go
Closes: nothing
Refine logs and removed duplications
---
I have...
I have...
> refactor: refine logs

- config/provider_examples/hyperliquid_example.yml
- scripts/pre_setups/init_hyperliquid_only_with_node.sh
- specs/mainnet-1/specs/hyperliquid.json
Closes: #XXXX
The Hyperliquid spec supported REST API interface, but Hyperliquid nodes can't serve REST. So I removed it
---
I have...
I have...
> fix: Remove REST from Hyperliquid spec

- protocol/metrics/provider_metrics.go
- protocol/metrics/provider_metrics_manager.go
- protocol/rpcprovider/provider_state_machine.go
- protocol/rpcprovider/rpcprovider_server.go
Closes: nothing
Added metrics:
* Total requests handled per function / api name (counter)
* Total errors per function / api name (counter)
* Current in-flight requests (gauge)
* Latency for request per function / api name (gauge)
---
I have...
I have...
> feat: :sparkles: added new provider metrics

- protocol/rpcconsumer/relay_state.go
Closes: #XXXX
---
I have...
I have...
> feat: archive on first retry

- x/protocol/types/params.go
Closes: #XXXX
---
I have...
I have...
> chore: up protocol version to 5.4.1

- specs/mainnet-1/specs/hedera.json
Closes: #XXXX
---
I have...
I have...
> feat: add hedera spec

- protocol/lavasession/consumer_session_manager.go
- protocol/rpcconsumer/relay_processor.go
- protocol/rpcconsumer/relay_processor_test.go
Fixes are done in the following:
1. Retry condition when the quorum is not met
2. Calculation of actualQuorumNeeded number after every Retry
3. Error represented to the user after quorum is not met
> fix: The following has been fixed in the quorum feature

- specs/mainnet-1/specs/near.json
Closes: #XXXX
---
I have...
I have...
> fix(NEART-spec): adding sharding verifications to NEAR testnet

- protocol/metrics/provider_metrics.go
- protocol/metrics/provider_metrics_manager.go
- protocol/rpcprovider/rpcprovider_server.go
Added a new metric for the provider to propagate its actual latency upon relays
Closes: #XXXX
---
I have...
I have...
> feat(provider): add actual provider latency metric

- protocol/common/cobra_common.go
- protocol/rpcconsumer/rpcconsumer.go
- protocol/rpcprovider/rpcprovider.go
- protocol/statetracker/state_tracker.go
- utils/keeper/spec.go
- utils/keeper/spec_integration_test.go
- utils/keeper/spec_test.go
Closes: #XXXX
---
I have...
I have...
> feat: optimize GitHub API usage for spec fetching
